
logging:
  level:
    com.rackspace.salus.telemetry.api: debug
salus.services:
  monitor-management-url: http://localhost:8089
  resource-management-url: http://localhost:8085
  event-management-url: http://localhost:8087
  agent-catalog-management-url: http://localhost:8090
spring:
  profiles:
    include: "unsecured"