
api:
  public:
    version: "1.0"
etcd:
  url: http://localhost:2479
management.endpoints.web.exposure.include: "health,jolokia,metrics"
management:
  metrics:
    export:
      statsd:
        flavor: ${statsd.flavor:telegraf}
        host: ${statsd.host:localhost}
        port: ${statsd.port:8125}
        enabled: ${statsd.enabled:false}
      influx:
        db: telemetry-ambassador
        host: ${statsd.host:localhost}
        port: ${statsd.port:8086}
        enabled: ${influx.enabled:false}
server:
  servlet:
    context-path: "/v${api.public.version}"