
etcd:
  url: http://localhost:2479
management.endpoints.web.exposure.include: "health,jolokia,metrics"
management:
  metrics:
    export:
      statsd:
        flavor: ${statsd.flavor:telegraf}
        host: ${statsd.host:localhost}
        port: ${statsd.port:8125}
        enabled: ${statsd.enabled:false}
      influx:
        db: telemetry-ambassador
        host: ${statsd.host:localhost}
        port: ${statsd.port:8086}
        enabled: ${influx.enabled:false}
server:
  port: 8888
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
    exception-handlers-enabled: true
logging:
  level:
    graphql.servlet.internal.ApolloSubscriptionKeepAliveRunner: error