server:
  port: 8888
logging:
  level:
    com.rackspace.salus: debug
salus.services:
    monitor-management-url: http://localhost:8089
    resource-management-url: http://localhost:8085
    event-management-url: http://localhost:8087
    presence-monitor-url: http://localhost:8083
    agent-catalog-management-url: http://localhost:8090
    policy-management-url: http://localhost:8091
spring:
  profiles:
    include: unsecured